// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // spotit-62cab project (must match google-services.json / Realtime Database URL)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNzqwQFpdLPsIEvJ8VAW0diEUVqf2DQ58',
    appId: '1:1095873417567:web:85c0280abfe34aa5cbe6ea',
    messagingSenderId: '1095873417567',
    projectId: 'spotit-62cab',
    authDomain: 'spotit-62cab.firebaseapp.com',
    storageBucket: 'spotit-62cab.firebasestorage.app',
    databaseURL: 'https://spotit-62cab-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNzqwQFpdLPsIEvJ8VAW0diEUVqf2DQ58',
    appId: '1:1095873417567:android:85c0280abfe34aa5cbe6ea',
    messagingSenderId: '1095873417567',
    projectId: 'spotit-62cab',
    storageBucket: 'spotit-62cab.firebasestorage.app',
    databaseURL: 'https://spotit-62cab-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNzqwQFpdLPsIEvJ8VAW0diEUVqf2DQ58',
    appId: '1:1095873417567:ios:85c0280abfe34aa5cbe6ea',
    messagingSenderId: '1095873417567',
    projectId: 'spotit-62cab',
    storageBucket: 'spotit-62cab.firebasestorage.app',
    databaseURL: 'https://spotit-62cab-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.spotit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNzqwQFpdLPsIEvJ8VAW0diEUVqf2DQ58',
    appId: '1:1095873417567:ios:85c0280abfe34aa5cbe6ea',
    messagingSenderId: '1095873417567',
    projectId: 'spotit-62cab',
    storageBucket: 'spotit-62cab.firebasestorage.app',
    databaseURL: 'https://spotit-62cab-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.spotit',
  );
}
